# Site settings 配置站点
title: 'bogwarts comics'
description: 'wholesome slice of life coding comics'
keywords: 'webcomic, coding comics, comics, xkcd'
url: 'https://bogwarts.github.io' # your host

nav:
  home: '/'
  # timeline: '/timeline.html'
  about: '/about.html'
  # tags: '/tags.html'

# 博主
author: true
name: 'bea'
NickName: 'coderbea'
webtitle: 'bogwarts'
bio: 'bea is a software engineer in san francisco'
about: true
aboutyou: 'I am your standard engineer that likes to party. indoors. by myself. with my computer.'
portraits: '/assets/profile.png'

# SNS
SNS: true
SNS-icon: #['Facebook', 'Twitter', 'instagram']
  mail: 'mailto:bogwartscomics@gmail.com'
  instagram: 'https://instagram.com/coderbea'
  Twitter: 'https://twitter.com/coderbea'

paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2020

# Markdown
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'


# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['instagram', 'twitter', 'facebook']

google: false
google-ID: ''

color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
